### ISSUE TITLE
Parse XML posted on the URL

### ISSUE THREAD

**Issue by awaisqarnise** [orchestral/parser#12]
Hi, 
I need to parse XML that comes as POST. I am capturing that XML like
 
     $xml_document = file_get_contents('php://input');

But when I gives it to parse like 

      $xml = XmlParser::load($xml_document);

It is giving me 

 InvalidContentException in Reader.php line 40:
Unable to parse XML from string.

Why is it taking as string? When I see the error log it shows like

   at Reader->load('<?xml version="1.0" encoding=".......') putting it in single quote.  Why is it putting single quote and telling me unable to parse XML from string?

**Comment by crynobone** [comment]
```php
XmlParser::extract($document);
```

**Comment by awaisqarnise** [comment]
Dude you need to write a complete detailed documentation of your package :)

**Comment by crynobone** [comment]
> Dude you need to write a complete detailed documentation of your package :)

<https://github.com/orchestral/parser/edit/master/README.md> It's open sourced, you're more than welcome to contribute :)
