### ISSUE TITLE
Parsing complex XML

### ISSUE THREAD

**Issue by mxmtsk** [orchestral/parser#15]
Hi,

I have a question regarding the parser. I've been able to parse a lot of XML with your package but this more complex XML gives me headache:
https://gist.github.com/mxmtsk/7a52f984bca9099f8c3f

Could you help me or provide an example of how to parse this list (value and key are in two different elements for each entry)!

Thanks,
Max

**Comment by crynobone** [comment]
> Could you help me or provide an example of how to parse this list (value and key are in two different elements for each entry)!

It just not possible with parser at the moment.

**Comment by crynobone** [comment]
Mark as "open for contribution" if anyone can solve this. Please send the PR to <https://github.com/laravie/parser>.
