### ISSUE TITLE
Having trouble with multi dimensional array

### ISSUE THREAD

**Issue by rohitkhatri** [orchestral/parser#20]
<statistics>
        <shots home="12" guest="2">
            <on_goal home="7" guest="2"/>
            <goals home="1" guest="1"/>
            <held_shots home="6" guest="1"/>
        </shots>
        <failed_shots home="5" guest="0">
            <goal_frame home="0" guest="0"/>
            <missed home="5" guest="0"/>
            <blocked home="0" guest="0"/>
        </failed_shots>
        <possession home="63" guest="37"/>
        <corners home="3" guest="5"/>
        <offsides home="4" guest="2"/>
        <freekicks home="16" guest="11"/>
        <penaltykicks home="0" guest="0"/>
        <yellow_cards home="3" guest="3"/>
        <red_cards home="0" guest="0"/>
        <substitutions home="3" guest="2"/>
    </statistics>

    $xml = XmlParser::load($xmlString);
    $statistics = $xml->parse([
        'shots' => [
            'home' => ['uses' => 'shots::home'],
            'guest' => ['uses' => 'shots::guest'],
        ],
    ]);

It throws error

    ErrorException in Document.php line 110:
    Undefined index: default

**Comment by crynobone** [comment]
Should be fixes via latest `laravie/parser`, run `composer update`.
