### ISSUE TITLE
Installed 3.0 on Laravel 5.2.29

### ISSUE THREAD

**Issue by kickthemooon** [orchestral/parser#21]
I accidently installed the 3.0 parser version on laravel 5.2
and things arent really as they should be.

Im using phpstorm and storm will not recognize the XmlParser facade, wont give me the option to use the facade.

And im trying to update the parser to 3.2 without luck... 

any suggestions?

**Comment by crynobone** [comment]
Can't you change the version constraint to `^3.2`?

**Comment by kickthemooon** [comment]
composer.json:
```
"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "orchestra/parser": "^3.2"
    },
```
composer response on composer update:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
```

**Comment by crynobone** [comment]
what does `composer show` output?

**Comment by kickthemooon** [comment]
orchestra/parser v3.2.1 - XML Document Parser for Laravel and PHP
seems its updated.

Then how do I use 
```
XmlParser::load('');
```

What do I include in the "use" section at the top of the controller?

**Comment by crynobone** [comment]
You can either use

```php
use XmlParser; // if you include the installation process to `app.aliases` config.
```

or 

```php
use Orchestra\Parser\Xml\Facade as XmlParser;
```

**Comment by kickthemooon** [comment]
Ok, ill try. I included the alias but its just strange for me that php storm is no recognizing it. 
Its not giving me the option of xmlparser like it gives me the option for DB:: as an example.
But ill try
```
use Orchestra\Parser\Xml\Facade as XmlParser;
```

**Comment by crynobone** [comment]
I assume you're using some sort of IDE helper package for Laravel. Well, that package can only register the default facades that come with Laravel.
