### ISSUE TITLE
Multidimensional arrays

### ISSUE THREAD

**Issue by kickthemooon** [orchestral/parser#23]
so i have this:

```
<Country name="Iceland" id="ISL">
  <Competition id="ISL_1" name="Iceland 1" event_name="Premier League" sport="soccer" levels_on_pyramid="0" competition_type="league" image="" timestamp="0"/>
  <Competition id="ISL_2" name="Iceland 2" event_name="1. Division" sport="soccer" levels_on_pyramid="0" competition_type="league" image="" timestamp="0"/>
  <Competition id="ISL_C_1" name="Iceland Cup 1" event_name="Iceland Cup" sport="soccer" levels_on_pyramid="0" competition_type="cup" image="" timestamp="0"/>
</Country>
<Country name="India" id="IND">
  <Competition id="IND_1" name="India 1" event_name="I League" sport="soccer" levels_on_pyramid="0" competition_type="league" image="" timestamp="0"/>
</Country>
<Country name="Indonesia" id="INA">
  <Competition id="INA_1" name="Indonesia 1" event_name="Super Liga" sport="soccer" levels_on_pyramid="0" competition_type="league" image="" timestamp="0"/>
</Country>
<Country name="International" id="INT">
  <Competition id="INT_1" name="AFC Champions League 1" event_name="AFC Champions League" sport="soccer" levels_on_pyramid="0" competition_type="league" image="" timestamp="0"/>
  <Competition id="INT_2" name="Africa Cup of Nations 1" event_name="Africa Cup of Nations" sport="soccer" levels_on_pyramid="0" competition_type="cup" image="" timestamp="0"/>
  <Competition id="INT_30" name="Asian Cup 1" event_name="Asian Cup" sport="soccer" levels_on_pyramid="0" competition_type="cup" image="" timestamp="0"/>
  <Competition id="INT_4" name="CAF Champions League 1" event_name="CAF Champions League" sport="soccer" levels_on_pyramid="0" competition_type="league" image="" timestamp="0"/>
  <Competition id="INT_3" name="Champions League" event_name="UEFA Champions League" sport="soccer" levels_on_pyramid="1" competition_type="league" image="" timestamp="0"/>
  <Competition id="INT_6" name="Club Friendlies 1" event_name="Club Friendlies" sport="soccer" levels_on_pyramid="0" competition_type="league" image="" timestamp="0"/>
  <Competition id="INT_35" name="CONCACAF Champions Cup 1" event_name="CONCACAF Champions Cup" sport="soccer" levels_on_pyramid="0" competition_type="cup" image="" timestamp="0"/>
  <Competition id="INT_34" name="CONCACAF Gold Cup 1" event_name="CONCACAF Gold Cup" sport="soccer" levels_on_pyramid="0" competition_type="cup" image="" timestamp="0"/>
  <Competition id="INT_9" name="Confederations Cup 1" event_name="Confederations Cup" sport="soccer" levels_on_pyramid="0" competition_type="cup" image="" timestamp="0"/>
  <Competition id="INT_10" name="Copa America 1" event_name="Copa America" sport="soccer" levels_on_pyramid="0" competition_type="league" image="" timestamp="0"/>
```

Now I need all competitions that belong to a country

I am trying something like this but not working:

```
$xml_leagues2 = $xml_comp->parse([
      'data' => ['uses' => 'Country[::id>country_id,Competition[::id>competition_id]]', 'default' => null],
]);
```

Any suggestions?

**Comment by kickthemooon** [comment]
```
$xml_leagues = $xml_comp->parse([
            'data' => ['uses' => 'Country[Competition::id>id,Competition::name>name,Competition::event_name>event_name]', 'default' => null],
        ]);
```

This returns me only the first competition...

**Comment by crynobone** [comment]
Don't think it can parse that, however I'm open for PR if you can make that happen.

**Comment by tmphong** [comment]
<Item>
                    **<ItemIDs>
                        <IdQualifier>UP</IdQualifier>
                        <Id>
                            <![CDATA[49404]]>
</Id>
                    </ItemIDs>
                    <ItemIDs>
                        <IdQualifier>VN</IdQualifier>
                        <Id>
                            <![CDATA[IH-BL-CT2110W]]>
</Id>
                    </ItemIDs>**
                    <Quantities>
                        <QtyQualifier>39</QtyQualifier>
                        <QtyUOM>EA</QtyUOM>
                        <Qty>12</Qty>
                    </Quantities>
                    <PackSize>1</PackSize>
                    <Inners>12</Inners>
                    <EachesPerInner></EachesPerInner>
                    <InnersPerPacks></InnersPerPacks>
                    <Size>
                        <![CDATA[]]>
</Size>
                    <Measurement>
                        <MeasureQual>WT</MeasureQual>
                        <MeasureValue>1</MeasureValue>
                    </Measurement>
                </Item>

How I can get set up $xml->parse([ **??** ]) to get 2 variables?

**Comment by quinhone** [comment]
How do I do parse using foreach? Exemple:

<categories>
    <category id="1">
        <name>Name A</name>
    </category>
    <category id="2">
        <name>Name B</name>
    </category>
    <category id="3">
        <name>Name C</name>
    </category>
</categories>

**Comment by SpinyMan** [comment]
$xml_leagues = $xml_comp->parse([
  'data' => ['uses' => 'Country.Competition[::id>id,::name>name,::event_name>event_name]', 'default' => null],
]);

**Comment by lchachurski** [comment]
@SpinyMan Your solution will parse only Icelands competitions.
