### ISSUE TITLE
Problems with usage 

### ISSUE THREAD

**Issue by AlbertoTurmina** [orchestral/parser#26]
I did all the installations steps and is located in /vendor/orchestra, also insert the new provider and aliases on config/app.php.

When i tryed to use inside my controller, got this error 
`FatalErrorException in BillingController.php line 63:
Class 'Modules\Billing\Http\Controllers\Admin\XmlParser' not found`

Also tryed with:

use Orchestra\Parser as XmlParser;
public function __construct(BillingRepository $billing, XmlParser $XmlParser)
    {
        parent::__construct();

        $this->billing = $billing;
        $this->XmlParser = $XmlParser;

but still no found the class
`ReflectionException in Container.php line 795:
Class Orchestra\Parser does not exist`

Can some one help?

**Comment by crynobone** [comment]
There no documentation that has even suggest injecting a facade or `Orchestra\Parser`. 

Please read the documentation.
