### ISSUE TITLE
Read fields with same name

### ISSUE THREAD

**Issue by AlbertoTurmina** [orchestral/parser#28]
How can i read fields with the same name?
`
<det nItem="1">
<prod>
<cProd>01349</cProd>
</prod>
</det>
<det nItem="2">
<prod>
<cProd>01350</cProd>
</prod>
</det>
`

**Comment by crynobone** [comment]
Look at <https://github.com/laravie/parser/blob/master/tests/Xml/DocumentTest.php#L167-L194> for example.

**Comment by AlbertoTurmina** [comment]
@crynobone there is no example like my case

**Comment by crynobone** [comment]
Then most likely it's not supported.

Would be nice if you can come out with a PR to make it support, but I don't think I be looking into this right now.

**Comment by AlbertoTurmina** [comment]
SOLVED:
'det' => ['uses' => 'NFe.infNFe.det[::nItem>nItem,prod.CFOP,prod.cProd]'],
