### ISSUE TITLE
Error:Unable to parse XML from string.

### ISSUE THREAD

**Issue by hotamy** [orchestral/parser#30]
[code](http://imgur.com/a/b61im)

**Comment by stockhausen** [comment]
can you give dump($path); ???

**Comment by stockhausen** [comment]
https://laravel.com/docs/5.3/filesystem#retrieving-files

**Comment by hotamy** [comment]
http://imgur.com/a/DYeoo

**Comment by crynobone** [comment]
Why not use `extract` method instead of `load`?

**Comment by hotamy** [comment]
??
http://imgur.com/a/pfBGb

**Comment by crynobone** [comment]
You are asking how to load xml from a string, correct? `extract` is the way to do it. So stop putting the xml string to a file and expect giving a path would magically solve anything.

**Comment by hotamy** [comment]
sorry ~~ i am trying another method.
thanks~

**Comment by crynobone** [comment]
```php
$payload = '<api>
    <user followers="5">
        <id>1</id>
        <email>crynobone@gmail.com</email>
    </user>
</api>';

$xml = XmlParser::extract($payload);
$user = $xml->parse([
    'id' => ['uses' => 'user.id'],
    'email' => ['uses' => 'user.email'],
    'followers' => ['uses' => 'user::followers'],
]);
```
