### ISSUE TITLE
Parsing nested XML into nested objects not arrays

### ISSUE THREAD

**Issue by ao-tigran** [orchestral/parser#31]
I'm dealing with this XML:

`<Employee>
    <FirstName>Daniel</FirstName>
    ...
    <InsuranceData>
        <EndDate>10/11/2016</EndDate>
        <EndTime>17:34</EndTime>
    </InsuranceData>
</Employee>`

I parse the insurance data:

`'insurance' => ['uses' => 'InsuranceData[EndDate,EndTime]'],`

But I don't want to have an array as employee has only on insurance, then I need to do a trick to get rid of it:

`$result['insurance'] = $result['insurance'][0];`

Is there a way to handle this?

**Comment by crynobone** [comment]
Not at the moment, and I don't think there any plan to add it.

**Comment by ao-tigran** [comment]
Thanks for the quick response.
