### ISSUE TITLE
Array Within Multidimensional Array

### ISSUE THREAD

**Issue by matthewmnewman** [orchestral/parser#32]
Looking at some of the other issues in relation to this topic i am unable to find a solution in which i can parse more than one item from the [Options] array within the [Vehicles] array.

At the moment into will only retrieve the first array but i am wondering is it possible to to do this with this parser?

**For Example:**

<img width="492" alt="screen shot 2016-10-21 at 11 07 23" src="https://cloud.githubusercontent.com/assets/10243428/19594796/afa1abb4-977e-11e6-8414-01aa841407f9.png">

  ```
  // Parse XML
    $app = new Container;
    $document = new Document($app);
    $reader = new Reader($document);
    $storage = Storage::disk('xml')->get('cars.xml');

    $xml = $reader->extract($storage);

    $extract = $xml->parse([
        'Vehicles' => ['uses' => 'VEHICLES[CENTRENO,ID,OPTIONS.ITEM]']
    ]);
```

**Comment by crynobone** [comment]
Should already be possible. https://github.com/laravie/parser/blob/master/tests/Xml/DocumentTest.php#L99-L114

**Comment by bezner** [comment]
I got the same problem and the code:

```
    $extract = $xml->parse([
        'Vehicles' => ['uses' => 'VEHICLES[CENTRENO,ID,OPTIONS.ITEM]']
    ]);
```
generally works BUT it returns only the first ITEM child node value instead of parsing them all into an array of values. 

Is there a workaround for to achieve that? I really need that feature in a case I work with. I'm using version 3.3 of the package.

**Comment by LucaColombi** [comment]
similar situation, need to list/group/aggregate multiple repeated subnodes, can take only the first

**Comment by matthewmnewman** [comment]
> similar situation, need to list/group/aggregate multiple repeated subnodes, can take only the first

No disrespect to the author of this project but we ended up utilizing another parser to resolve the above.
[Alternative Package](https://github.com/nathanmac/Parser)

**Comment by honghialinh** [comment]
<img width="446" alt="Screen Shot 2020-03-18 at 6 02 14 PM" src="https://user-images.githubusercontent.com/26892824/76954263-a548ef80-6942-11ea-96a0-2706d4131ffd.png">

I have an XML file witch the above content. 
```
$file = $xml->parse([ 'book' => ['uses' => 'book[id>root_id,subject.name>subject_name,collection.internal_name,collection.name,collection.image,collection.products.product)]'],
        ]);
```
Please help me how to parse products.product to array. like this:
<img width="442" alt="Screen Shot 2020-03-18 at 6 13 54 PM" src="https://user-images.githubusercontent.com/26892824/76955184-4be1c000-6944-11ea-8415-04272ae5edcd.png">
Many thanks !!!
