### ISSUE TITLE
Namespacing issue

### ISSUE THREAD

**Issue by crslp** [orchestral/parser#34]
Hey people.

I am quite sure, this is due to my misunderstanding of the namespace-concept of PHP. I am sorry for that. But this is holding me back from moving on with my app.

So, by following the installation-instructions, I can't get your package get to work with Laravel 5.3. The installation via composer is smooth, but I don't know and can't figure out by myself, what kind of "use ..." term I have to put into my controller.

I appreciate any help. Thank you!

**Comment by armababy** [comment]
Hey,

You can see psr-4 namespace registered in composer [here](https://github.com/orchestral/parser/blob/master/composer.json#L15).
Also, you can see namespace in each of packages files [for example](https://github.com/orchestral/parser/blob/master/src/Xml/Reader.php#L3)
Also, you can use facade if you added it to your aliases as described in documentation.
