### ISSUE TITLE
using orchestral or laravie to parse this kind of document in laravel and how?

### ISSUE THREAD

**Issue by repositoryofexcellence** [orchestral/parser#35]
Hello. I have a that kind of xml and i want to parse this with laravel. I saw that you have two different parser for laravel and im asking that which one should i use for parsing this kind of document and how? Will be appreciated if u help.

> <HOTELS>
	<Hotel>
	<pictures>
	<picture>http://www.suaytur.com/Pictures/H-1017105726878.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-925231348280.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-925231349756.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-925231350905.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-92523141995.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-925231419517.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-925231420100.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-92523147103.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-925231433729.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-925231529936.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-925231432736.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-92523153861.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-92523146280.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-925231449313.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-925231451757.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-92523154728.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-925231518132.JPEG</picture>
	<picture>http://www.suaytur.com/Pictures/H-92523151875.JPEG</picture>
	</pictures>
	</Hotel>
  </HOTELS>

**Comment by crynobone** [comment]
Laravie build the XML parser for any php project, and orchestra focus on integration with Laravel. Check the example and test it out.
