### ISSUE TITLE
Repeated tags

### ISSUE THREAD

**Issue by rafaelvenera** [orchestral/parser#36]
Hey Guys, how to parse attributes for example:

`<user` id="1"> `<info>` `<name>John</name>` `</info>` `</user>`
`<user` id="2"> `<info>` `<name>Mary</name>` `</info>` `</user>`

I tried to do this:
'event'  => ['uses' => 'user[::id>id, info, name]'],

Did not work :(

Any thoughts?

Thanks...

**Comment by shazadmaved** [comment]
Hi @rafaelvenera  Did you find the solution for this?
