### ISSUE TITLE
instalation

### ISSUE THREAD

**Issue by jaroslawziolkowski** [orchestral/parser#4]
When I try install library on L5 stable I see error:
 Problem 1
    - The requested package orchestra/parser could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

**Comment by crynobone** [comment]
Can you pass the full `composer.json` content
