### ISSUE TITLE
Parsing complex XML

### ISSUE THREAD

**Issue by deepslam** [orchestral/parser#40]
Hello!
I have a problem. Help me please if you can.

My problem is:

I have XML:

```
<item>
   <caption></caption>
   <image></image>
   <image></image>
   ...
   <image></image>
</item>
... items with the same structure.
```

How can I parse it into array items with images subarray?

Thank you very much!

Sincerely, Dmitry

**Comment by crynobone** [comment]
Based on my understanding of the code, it should already possible, however if there's a bug do send a failing PR with the relevant test cases so we can look into it.

**Comment by deepslam** [comment]
Can you help me with the right config for this? Thank you!
I understood how I can parse <item> tags, but didn't understand how I can parse image into images array of each item.

Sincerely, Dmitry.
