### ISSUE TITLE
What about a file with multiple users?

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [orchestral/parser#43]
For example:
``<api>
    <user followers="5">
        <id>1</id>
        <email>crynobone@gmail.com</email>
    </user>
    <user followers="9">
        <id>2</id>
        <email>anotheruser@gmail.com</email>
    </user>
    <user followers="9">
        <id>3</id>
        <email>user3@gmail.com</email>
    </user>
</api>``

**Comment by shazadmaved** [comment]
@EdnaldoNeimeg have you found a solution for this?
