### ISSUE TITLE
Multiple Array's

### ISSUE THREAD

**Issue by MikePNL87** [orchestral/parser#45]
How Can i parse through the following xml to see all DiscountGroups Discount and GroupCodes?

`<Customer Name="A. Timmerman's IJzerhandel BV" GLN="8714231355649">
<TermsLine>
<DiscountGroup>
<GroupCode>GPF_PVD_Algemeen</GroupCode>
<Discount type="percentage" position="A">50</Discount>
</DiscountGroup>
</TermsLine>
<TermsLine>
<DiscountGroup>
<GroupCode>GPF_PVD_Divers</GroupCode>
<Discount type="percentage" position="A">40</Discount>
</DiscountGroup>
</TermsLine>`

**Comment by lbeckerfive** [comment]
Nice question and I hope we'll get a answer soon :-)
