### ISSUE TITLE
Facade XmlParser not found

### ISSUE THREAD

**Issue by MirlanJA** [orchestral/parser#47]
Hi, Im use Laravel 5.5, after installation and configuration this package, I tried use XmlParser facade and after a get error  "Class 'App\Http\Controllers\Admin\XmlParser' not found", how i can solve this problem?

**Comment by crynobone** [comment]
Read the installation instruction.

**Comment by robbanl** [comment]
Not documented, but try \XmlParser::load instead of XmlParser::load in your business logic.

**Comment by princekdwivedi** [comment]
I use like $xml = \XMLParser::read($xml_doc); but i get same error
