### ISSUE TITLE
Multiple data with attributes

### ISSUE THREAD

**Issue by kikky7** [orchestral/parser#53]
Example xml:

```
<trips>
    <trip name="Destination name" id="1000">
        <dates>
            <data from="x" to="y" price="1000"></data>
            ...
        </dates>
    </trip>
    ...
</trips>
```
What I am trying to get is:
```
'trips' => [
    0 => [
        'name' => 'Destination name',
        'id' => 1000,
        'dates' => [
            0 => [ 'from' => 'x', 'to' => 'y', 'price' => 1000 ],
            1 => [ ... ],
            ...
        ],
    ],
    1 => [ ... ],
    ...
]
```
Test code:
```
'trips' => [
    'uses' => 'trip[::name,::id,dates]',
]
Output (not good):
[
    '::name' => 'Destination name',
    '::id' => 1000,
    'dates' => null
]
---
'trips' => [
    'uses' => 'trip[name,id,dates]',
]
Output: everything is null
```

Can such xml be parsed with this package in the way I want?

**Comment by kikky7** [comment]
Why closing the issue without explanation? As I can see, every issue is closed without the solution or explanation and the overall documentation is poorly written.
You feel better when your issue list is empty?

**Comment by crynobone** [comment]
It's not an issue and I don't have time to look and understand everyone else problem. 

I used to helps but everyone just move on when they solve the problem, so yeah the documentation remain as it is. You can look at the existing tests.
