### ISSUE TITLE
Tags can't be renamed properly

### ISSUE THREAD

**Issue by Dennisvb** [orchestral/parser#54]
First of all, love this package! 

I have read the DocumentTest.php and found the ability to parse tags as well. 
I tried to rename the key like this:

`$data = $document->parse([
 'users' => ['uses' => 'user[name,age,language(@=@)>languages]']]);`

which resulted in a languages array inside another languages array:

`1 => array:3 [
      "name" => "laura"
      "age" => "19800505"
      "languages" => array:1 [
        "languages" => array:3 [
          0 => "de"
          1 => "en"
          2 => "nl"
        ]
      ]
]`

I tried a lot, but can't get it to work. Any ideas?

Dennis

**Comment by crynobone** [comment]
Could you add above use case to <https://github.com/laravie/parser/blob/1.2/tests/Xml/DocumentTest.php> so I can see the actual structure.
