### ISSUE TITLE
Namespace for the packege "orchestral/parser" in laravel

### ISSUE THREAD

**Issue by lvsharmila** [orchestral/parser#57]
What is the namespace to be used in controller for the package Orchestral/parser and how to used it in laravel.

**Comment by greylegface** [comment]
Once you have installed the package, make sure you add the providers and the Facade to your config/app.php.

Then, you can either call the package: /XMLParser::

or at the top use XMLParser;

and then use it.

(This assumes that you have called it "XMLParser" in your config/app.php")
