### ISSUE TITLE
use laravie 1.3

### ISSUE THREAD

**Issue by ollakalla** [orchestral/parser#59]
Hi Mior,
     I'm Ahmed who make contribution on laravie and add Multilevel on array.
now i'm using this plugin but it is still require  laravie 1.2 , can you change it to laravie 1.3 on last branch orchestra/parser 3.6, so i can used it, and also there are people asks about that feature, and it will be good thing :)
instead of updating the code on vendor files

**Comment by crynobone** [comment]
`"laravie/parser": "^1.2"` can already resolve to `1.2.0` to anything lower than `2.0.0`.

Please check whether you met the minimum requirement of php `5.6.0`.

**Comment by ollakalla** [comment]
I figure out the problem, the laravie is installed from cache.
i tried to clear composer cache by `composer clear-cache` , but still installed from cache :(
