### ISSUE TITLE
Read all entries

### ISSUE THREAD

**Issue by rzimin** [orchestral/parser#6]
How to read all entries from XML?
$xml->parse is giving only the first child.

**Comment by crynobone** [comment]
Could you provide a full example of what you trying to achieve.

**Comment by seongbae-ml** [comment]
I think rzimin means that if there are multiple users in your example, how would it work.  I was curious about same thing.

**Comment by crynobone** [comment]
Here's some examples <https://github.com/orchestral/parser/blob/master/tests/Xml/DocumentTest.php#L74-L177>

So 

```xml
<api>
    <user>
        <id>1</id>
        <name>Mior Muhammad Zaki</name>
    </user>
    <user>
        <id>2</id>
        <name>Taylor Otwell</name>
    </user>
</api>
```

```php
$app = new Illuminate\Container\Container;
$document = new Orchestra\Parser\Xml\Document($app);
$reader = new Orchestra\Parser\Xml\Reader($document);

$xml = $reader->load('path/to/above.xml');
$user = $xml->parse([
    'users' => ['uses' => 'user[id,name]'],
]);
```

**Comment by sileence** [comment]
@crynobone if I have this XML:

```
<api>
    <user>
        <id>1</id>
        <name>Mior Muhammad Zaki</name>
    </user>
    <user>
        <id>2</id>
        <name>Taylor Otwell</name>
        <tag>PHP</tag>
        <tag>Laravel</tag>
    </user>
</api>
```

Is there a way to retrieve the multiple tags per user as well?

**Comment by crynobone** [comment]
> Is there a way to retrieve the multiple tags per user as well?

I don't think so, does `'users' => ['uses' => 'user[id,name,tag]']` fail?

**Comment by crynobone** [comment]
Push code to support this. You should be able to use

```php
$app = new Illuminate\Container\Container;
$document = new Orchestra\Parser\Xml\Document($app);
$reader = new Orchestra\Parser\Xml\Reader($document);

$xml = $reader->load('path/to/above.xml');
$user = $xml->parse([
    'users' => ['uses' => 'user[id,name, tag(!=@)]'],
]);
```

**Comment by sileence** [comment]
Thank you for this change, sadly I forgot to mention I'm working with version `"orchestra/parser": "2.2.*"` Because I'm working in a Laravel 4 project.

**Comment by crynobone** [comment]
@sileence You can look at <https://github.com/laravie/parser> and configure it (but it seem that it doesn't play nicely with PHP build that enabled in travis-ci), probably due to some bug with regex parsing so please make sure you have the latest PHP version.

also I swap `tag(!=@)` to `tag(@=@)`

**Comment by crynobone** [comment]
Eh wait, that's not possible as well because laravie/parser depends on illuminate/support 5.0+

**Comment by sileence** [comment]
don't worry, as least I know this will be available when I start a new project that requires a nice XML parser :) Thank you @crynobone

**Comment by dj1974** [comment]
Hi but how to parse attribute for example :
<user id="1">
  <name> Smit</name>
</user>
<user id="2">
  <name>Jane</name>
</user>

anyone?

**Comment by dj1974** [comment]
<user id="1">

**Comment by dj1974** [comment]
How to parse attributes for example:

`<user id="1">
    <name>Smit</name>
</user>
<user id="2">
    <name>Jane</name>
</user>`

**Comment by mbarwick83** [comment]
^ +1...I'm running into a similar issue as @dj1974. I can do so via `'events' => ['uses' => 'event[::date,title,description]'],`. Note, the **::date**. But now the array key is labelled `::date` - which is not ideal. Any suggestions?

**Comment by crynobone** [comment]
`::date>date`

**Comment by versha000** [comment]
Hi Can you please suggest How Can I concat multiple Tags data while parsing . I want all actors with lang attribute is en_US . I am using credits.actor(@=@) it gives me array but I want to concat them . not an array because i want to insert this data directly to my DB column 
For Eg: 
<credits>
		<actor lang="el_GR">Ίαν Ρίτσαρντσον</actor>
		<actor lang="en_US">Ian Richardson</actor>
		<actor lang="el_GR">Σουζάνα Χάρκερ</actor>
		<actor lang="en_US">Susannah Harker</actor>
		<actor lang="el_GR">Μάιλς Άντερσον</actor>
		<actor lang="en_US">Miles Anderson</actor>
		<actor lang="el_GR">Νταϊάν Φλέτσερ</actor>
		<actor lang="en_US">Diane Fletcher</actor>
	</credits>
