### ISSUE TITLE
How to parse nested xml nodes

### ISSUE THREAD

**Issue by RichMechanics** [orchestral/parser#65]
Hello i have an issue parsing the following code:
`<conferences><conference>
		<title>Title of the conference</title>
		<content>Content of the conference</content>
		<date>2017-05-18</date>
		<link>http://esisa.ac.ma/iot_esisa/</link>
		<images>
			<image>images/mobile/conferences/NDIDO/1.jpg</image>
			<image>images/mobile/conferences/NDIDO/2.jpg</image>
			<image>images/mobile/conferences/NDIDO/3.jpg</image>
			<image>images/mobile/conferences/NDIDO/4.jpg</image>
			<image>images/mobile/conferences/NDIDO/5.jpg</image>
		</images>
	</conference>
</conferences>`

i'm using the following code to parse it : 
`$data = $xml->parse([
        'conferences' => ['uses' => 'conference[title,content,date,link,images]'],
     ]);`

the isssue here is that i can't get the array of images that is nested inside the conference node.

is there any way to parse to fix this ?

Thank you in advance

**Comment by skipper234** [comment]
@RichMechanics try this `images.image[@>image]` instead of images.
