### ISSUE TITLE
Not possible to upgrade Laravel to 5.7

### ISSUE THREAD

**Issue by gbesoain** [orchestral/parser#71]
Version 3.7.x is not being selected when upgrading Laravel to 5.7 from 5.6.38 

`Problem 1
    - Conclusion: don't install laravel/framework v5.7.2
    - Conclusion: don't install laravel/framework v5.7.1
    - orchestra/parser v3.6.0 requires illuminate/container ~5.6.0 -> satisfiable by laravel/framework[v5.6.38], illuminate/container[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9]`

**Comment by crynobone** [comment]
Done
