### ISSUE TITLE
Write a Wiki

### ISSUE THREAD

**Issue by redferret** [orchestral/parser#73]
I think it would be great if a wiki was written for more advanced demonstrations of the parser

Like how to parse
```xml
<Types name='something'>
 <Type name='type1'>Some Content</Type>
 <Type name='type2' />
</Types>
```

**Comment by crynobone** [comment]
Anyone are welcome to contribute by sending a Pull Request to update the current `README`.

**Comment by redferret** [comment]
Are there any resources at all? How can I learn to use this?
