### ISSUE TITLE
How to get data from "dc:" attributes?

### ISSUE THREAD

**Issue by qWici** [orchestral/parser#74]
XML:
```xml
<item>
    <title>...</title>
    <link>...</link>
    <guid>...</guid>
    <description>...</description>
    <dc:date>2018-10-18T13:58:00+00:00</dc:date>
</item>
```
How I can get data from `dc:date` attribute?

**Comment by skipper234** [comment]
Hi @qWici it seems that only `::` are parsed, so using dc:date should work,

example:
`'date' => ['uses' => 'dc:date']`
output:
`
array:1 [▼
  "date" => "2018-10-18T13:58:00+00:00"
]
`

**Comment by qWici** [comment]
@crynobone tnx
