### ISSUE TITLE
Only getting first child in a sub array

### ISSUE THREAD

**Issue by Rocky-27** [orchestral/parser#77]
A snippet of my XML data looks like this:

```
<id>
  <dep_tel>123456789</dep_tel>
  <dep_email>hello@example.com</dep_email>
  <pictures>
    <picture>example1.jpg</picture>
    <picture>example2.jpg</picture>
  </pictures>
</id>

<id>
  <dep_tel>123456789</dep_tel>
  <dep_email>hello@example.com</dep_email>
  <pictures>
    <picture>example3.jpg</picture>
    <picture>example4.jpg</picture>
  </pictures>
</id>
```

I am trying to create an array on id and then a sub array for the pictures. To do this I used the following code:

```
		$xml = XmlParser::load(storage_path('example.xml'));
		$data = $xml->parse([
			'id' => ['uses' => 'id[dep_tel,dep_email,pictures.picture]'],
		]);
```
Everything works fine apart from the subarray which only gets the first element so example1.jpg for instance. How would I go about including all picture tags inside pictures into each array?

**Comment by skipper234** [comment]
use something like `'id' => ['uses' => 'id[dep_tel,dep_email,pictures{picture}]'],` see the last example from the file [here](https://github.com/laravie/parser/blob/master/tests/Xml/DocumentTest.php).

**Comment by tforesti** [comment]
Hi,

Thank you for this answer, it helps me.

But with this given last exemple from the file [https://github.com/laravie/parser/blob/master/tests/Xml/DocumentTest.php](url), is it normal that the following code works :

`$data = $stub->parse([
	'product' => ['uses' => 'T_NEW_CATALOG.PRODUCT[NODE_ID>node_id,PRODUCT_FEATURES{FEATURE{FNAME>name}>feature}>product_features]'],
]);`

And this one doesn't work :

`$data = $stub->parse([
	'product' => ['uses' => 'T_NEW_CATALOG.PRODUCT[PRODUCT_FEATURES{FEATURE{FNAME>name}>feature}>product_features,NODE_ID>node_id]'],
]);`

I have changed the "NODE_ID>node_id" position : I put it from the begin to the end.

**Comment by skipper234** [comment]
hello @tforesti, I can confirm that this is true using the examples, one possible fix would be the following:

at [https://github.com/laravie/parser/blob/master/src/Xml/Document.php#L230](https://github.com/laravie/parser/blob/master/src/Xml/Document.php#L230) instead of this line,
```php
$result = $value;
```
using something like
```php
$result = array_merge($result, $value);
```
I have not yet tested all cases, later I'll test this a maybe open a PR, @crynobone ?

**Comment by crynobone** [comment]
As long as all the original tests runs green and new tests added to cover the new changes sure, send the the PR.

**Comment by Rocky-27** [comment]
Hey guys - not sure if I'm doing something wrong but I've tried:

    'id' => ['uses' => 'id[dep_tel,dep_email,pictures{picture}]'], (returns only the first result)
    'id' => ['uses' => 'id[dep_tel,dep_email,pictures{picture{{picture}}]'], (returns the correct amount of results but all with a null value)

Am I missing something fundamental in my approach?
