### ISSUE TITLE
XML from URL error

### ISSUE THREAD

**Issue by SajjadKharrazi** [orchestral/parser#78]
hi
when i use this:
`XmlParser::load("http://irsc.ut.ac.ir/events_list_fa.xml");`
or this:
`XmlParser::extract("http://irsc.ut.ac.ir/events_list_fa.xml");`
i get error: 

> Unable to parse XML from string.

when i call these in local, everything is ok, but when i upload to server ( cPanel ) i get that error

**Comment by crynobone** [comment]
I don't think I can replicate the issue, so it's unlikely I can help fix this. You need to consider troubleshooting the code on your own and try to fix it.
