### ISSUE TITLE
How to parse an XSD 

### ISSUE THREAD

**Issue by awaisqarnise** [orchestral/parser#8]
Hi currently I have an XCD that I need to parse. You can find XSD https://secure.ultracart.com/xml/ultracart.xsd can you please tell me how can I do that

**Comment by crynobone** [comment]
I would assume you want to read an XML based on that schema. Would you have an example of the XML, instead of giving me a full schema.

The tool is to convert XML to an array via PHP structure (as in the example), it doesn't convert the XML to array based on XSD.

**Comment by crynobone** [comment]
> How to parse an XSD?

No we don't parse XSD, we parse XML.
