### ISSUE TITLE
Parse at least 4 level nested:

### ISSUE THREAD

**Issue by ahmadwaliesipick** [orchestral/parser#80]
I want to parse a deeper level:

trying this:

 $result = $xml->parse([
            'Groups' => ['uses' => 'Group[Details.Section.Field(::FieldName=Value),Details.Section.Subreport(::Name=Name)>sections)>Subreports]','default' => null],
        ]);

anyone please suggest how can i get the require result?

**Comment by ahmadwaliesipick** [comment]
@crynobone  could you please help?

**Comment by crynobone** [comment]
It's not supported, [The Level 3 parsing was introduced based on PR made by community](https://github.com/laravie/parser/pull/14) and I have no plan to do it myself.

**Comment by ahmadwaliesipick** [comment]
@crynobone  thanks for quick response :-)
