### ISSUE TITLE
could single tag <nothing /> be parsed in parser

### ISSUE THREAD

**Issue by jses9160110** [orchestral/parser#81]
i git a problem when i parse a file include single tag 
and the error will like this "Laravie\Parser\InvalidContentException : Unable to parse XML from string."

I've tried 
$xml = XmlParser::load($content); 
not work too.

data in file like this 
![image](https://user-images.githubusercontent.com/46812083/56890964-82ed7f80-6aad-11e9-90b7-56272e357331.png)

error like this
![image](https://user-images.githubusercontent.com/46812083/56891031-b29c8780-6aad-11e9-8070-a839a3429528.png)

use like this
![image](https://user-images.githubusercontent.com/46812083/56891058-cb0ca200-6aad-11e9-8577-42a667de6328.png)

**Comment by crynobone** [comment]
This library uses `simplexml` under the hood, if `simplexml` can't parse the XML there nothing we can do about it.
