### ISSUE TITLE
Help with parsing a nested XML

### ISSUE THREAD

**Issue by Lindstromer** [orchestral/parser#85]
Hi. I've tried this quite some time now and can't find a similar example, so I'm trying with this issue instead.

The XML looks like this (simplified, more attributes on each tag, but overall the same:
```
<XML xmlns:q="http://url">
    <ITEMS>
        <ITEM Price="53.28">
            <PRICES>
                <PRICE Currency="DKK" />
            </PRICES>
        </ITEM>
        </ITEM>
    </ITEMS>
</XML>
```

What I'm trying to achieve is something structured like:
```
['items' => ['price' = '53.28', 'currency' = 'DKK']]
```

Can't really find a way to do it. Tried the following which sort of goes close to the desired result but doesn't work quite as expected with the Currency-part:
```
'uses' => 'ITEMS.ITEM[::Price>Price,PRICES.PRICE(::Currency=::Currency)>currency]'
```

**Comment by taunoM** [comment]
I have something similar and i would like to know the answer aswell. In my case i have:
`<transport>

    <items>
        <item code="1111" name="Some name" class="class_name">
        <data code="V1" content="C1"/>
        <data code="V2" content="C2"/>
        <data code="V3" content="C3" param="P3"/>
        <stocklevels>
        <stocklevel stock="AA" level="1"/>
        </stocklevels>
    </item>
</transport>`

Have tried many different approaches but none of them worked. I can get item info and it works well, i just cant understand how do i get data and stocklevels.

**Comment by crynobone** [comment]
<img width="1792" alt="Screenshot 2020-04-07 at 1 04 49 PM" src="https://user-images.githubusercontent.com/172966/78631981-64545300-78d0-11ea-8857-6e74f92d4665.png">
